INSERT INTO pins (pin_name, pin_description, image_link, latitude, longitude, pin_category_id, created_at, updated_at) VALUES

("Monument to the heroines of 1648 and 1848", "This is the city's first non-religious public art work, commemorating the women who played a role in the successful defense of Gyarmat Castle in 1648 and the 1848 revolution. Its cost was raised by donations, and an obelisk was erected. The ceremonial inauguration took place in 1908.", NULL, 48.075361, 19.289000, (SELECT id FROM pin_categories WHERE category_name = "Historical events"), NOW(), NOW()),

("World War I memorial", "This memorial was erected in memory of the citizens who died in the First World War. Its cost was raised through donations. The inauguration took place on October 20, 1929, in the square next to the county hall, in the presence of Governor Miklós Horthy. Since the area was temporary, the statue was moved to Palóc liget in 1937. The memorial was later renovated, including in February 2016, when missing parts of the lion were replaced based on archival photos and the model.", NULL, 48.074611, 19.290111, (SELECT id FROM pin_categories WHERE category_name = "Historical events"), NOW(), NOW()),

("Statue of the 16th home guard", "The erection of the World War I home guard memorial was initiated in 1935 by former members of the 16th Home Guard Infantry Regiment and was realized through donations. It was made by Jenő Körmendi-Frim. The memorial was inaugurated on October 27, 1937, in Hősök Square. The statue was moved to a secluded corner of Palóc liget in 1967, then returned to its original location in 1990. It was renovated in 2015.", NULL, 48.072389, 19.290472, (SELECT id FROM pin_categories WHERE category_name = "Historical events"), NOW(), NOW()),

("Madách statue", "The statue of Imre Madách, an outstanding personality of Hungarian literature, was made by Ferenc Sidló. The county issued a closed competition in 1935. The location for the statue was the square between the Courthouse and the County Hall. The ceremonial handover took place on September 26, 1937.", NULL, 48.076611, 19.289417, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Mikszáth bust", "Bust of Kálmán Mikszáth, made by Munkácsy Prize-winning sculptor Klára Herczeg. The city council decided on its erection in the late 1950s. The completed bust was inaugurated in 1961 in front of the county hall, in Köztársaság Square. The bust was renovated in 2012-2013.", NULL, 48.077028, 19.290722, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Petőfi statue", "Full-figure bronze statue of Sándor Petőfi, made by Tibor Borbás. It was handed over on March 15, 1977, in Palóc liget. The city's commemoration of the March 15th national holiday is held at the statue. Due to the shape of the cape stretched out by the extended arms, locals often mockingly call it the \"bat\".", NULL, 48.074917, 19.290889, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Jenő Komjáthy bust", "Sándor Győrfi's bust of Jenő Komjáthy was handed over in 1981 in Palóc liget.", NULL, 48.074583, 19.288861, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Ernő Kondor bust", "Barna Búza's pyrogranite bust of Ernő Kondor has stood in the courtyard of the Local History Collection since 1980.", NULL, 48.079972, 19.304139, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Lőrinc Szabó bust (2017)", "The new Lőrinc Szabó bust, created by Balassagyarmat sculptor György Petró, somewhat evokes the work by Miklós Borsos erected in 1977 and disappeared in 1997. The inauguration ceremony took place on October 3, 2017.", NULL, 48.074972, 19.289000, (SELECT id FROM pin_categories WHERE category_name = "Famous people"), NOW(), NOW()),

("Memorial plaque for driving out the Czechs", "Balassagyarmat's first public artwork created with public funds, commemorating the uprising of January 29, 1919. The memorial plaque was made by Hugó Keviczky. It was inaugurated on November 22, 1922, on the wall of the town hall , Horthy Miklós also gave a speech. Later, the bronze turul bird was removed and the plaque was turned over, engraving a new text on it. After the change of regime, it was turned back, and the turul was replaced with a copy.", NULL, 48.077389, 19.291083, (SELECT id FROM pin_categories WHERE category_name = "Memorial plaques"), NOW(), NOW()),

("Imre Madách memorial plaque", "Memorial plaque made by Hugó Keviczky. It was inaugurated on September 6, 1925, on the wall of the county hall during the opening of the economic exhibition. Festive speeches at the inauguration were given by House Speaker Béla Scitovszky, Governor Miklós Horthy, and MTA President Albert Berzeviczy. The inscription on the plaque was later partially erased , then made readable again or re-engraved based on civil initiative.", NULL, 48.076917, 19.290528, (SELECT id FROM pin_categories WHERE category_name = "Memorial plaques"), NOW(), NOW()),

("Kálmán Mikszáth memorial plaque", "Memorial plaque made by Hugó Keviczky. It was inaugurated on September 6, 1925, on the wall of the county hall during the opening of the economic exhibition. Festive speeches at the inauguration were given by House Speaker Béla Scitovszky, Governor Miklós Horthy, and MTA President Albert Berzeviczy. The inscription on the plaque was later partially erased, then after 1990, the \"fragmented\" words were made readable again.", NULL, 48.076833, 19.290361, (SELECT id FROM pin_categories WHERE category_name = "Memorial plaques"), NOW(), NOW()),

("Memorial plaque for the heroes of Balassi Bálint Grammar School", "Memorial plaque for the teachers and students who died in the First World War. The memorial plaque was made by János Branceisz. It was unveiled on June 10, 1926, at the celebration of the 25th anniversary of the establishment of the Hungarian Royal State Grammar School.", NULL, 48.075722, 19.294167, (SELECT id FROM pin_categories WHERE category_name = "Memorial plaques"), NOW(), NOW()),

("Statues of the courthouse", "Statues depicting a praetor symbolizing the guardian of the law and Iustitia, the Roman goddess of justice, on the main facade of the Balassagyarmat Courthouse. The building was handed over in 1912. Due to the deterioration of the statues, the originals were replaced with new statue copies in 2022-2023.", NULL, 48.076389, 19.288889, (SELECT id FROM pin_categories WHERE category_name = "Other works"), NOW(), NOW()),

("Boy Riding statue", "Bronze statue created by Károly Vasas. It was placed in front of the Ifjúság Úti Elementary School in 1968 , then relocated to the front of the Szabó Lőrinc Elementary School after the closure of the former.", NULL, 48.067806, 19.304778, (SELECT id FROM pin_categories WHERE category_name = "Other works"), NOW(), NOW()),

("Balassi Bálint statue", "Waist-up sculpted statue created by Péter Párkányi Raab, depicting Balassi while writing. It was inaugurated in 2004 in the garden of the Balassi Bálint Grammar School , at the former location of the Balassi stele. (Note: Not a public art work.)", NULL, 48.075833, 19.294167, (SELECT id FROM pin_categories WHERE category_name = "Non-public works"), NOW(), NOW()),

("Decorative plates", "A series of six pieces made of pyrogranite by ceramist Veronika Szabady, depicting three grotesque faces. They were exhibited in 1974 , then displayed on the facade of the main square building. Following the building's renovation, they were not returned to their original location but were moved to the Jánossy Gallery after restoration. (Note: Demolished/Relocated work.)", NULL, 48.076750, 19.291139, (SELECT id FROM pin_categories WHERE category_name = "Demolished works"), NOW(), NOW()),

("Lőrinc Szabó bust (Miklós Borsos, stolen)", "Bust made by Miklós Borsos. It was inaugurated on March 30, 1977, in Palóc liget. The bust was stolen in April 1997. (Note: Demolished/Stolen work. A new statue was later placed in its stead.)", NULL, 48.074972, 19.289000, (SELECT id FROM pin_categories WHERE category_name = "Demolished works"), NOW(), NOW());